### ISSUE TITLE
Broken links to images, etc. in the docs

### ISSUE THREAD

**Issue by pfalcon** [usagitoneko97/klara#5]
It seems that https://github.com/usagitoneko97/python-static-code-analysis/commit/1595f838b49f364d456a10673d42914f1d859118 broke various links around. E.g. in https://github.com/usagitoneko97/python-static-code-analysis/blob/master/lvn_optimization/readme.md , links to SVG images are broken . E.g. go to https://github.com/usagitoneko97/python-static-code-analysis/tree/master/lvn_optimization#113-algorithm-in-details, "IvnThird" pseudo-link is rendered instead of an image.

**Comment by usagitoneko97** [comment]
Close since LVN is removed.
